In [1]:
import numpy as n

In [171]:
#1
print(n.__version__)
n.show_config()

1.20.3


In [174]:
#2
n.info(n.add)

In [56]:
#3
a = n.random.randint(0,5, 15)
print(a)
n.all(a)

[2 2 1 0 4 2 2 2 1 3 4 4 1 1 4]


False

In [44]:
#4
a = n.random.randint(0,1,5)
print(a)
n.any(a)

[0 0 0 0 0]


False

In [59]:
#5
a = [1,2,n.inf]
n.isfinite(a)

array([ True,  True, False])

In [65]:
#6
a = [1,2,-n.inf, n.inf]
print(n.isposinf(a))
n.isneginf(a)

[False False False  True]


array([False, False,  True, False])

In [62]:
#7
a = [n.nan,1,2]
n.isnan(a)

array([ True, False, False])

In [63]:
#8
a = [n.nan,1,2]
print(n.iscomplex(a))
print(n.isreal(a))
print(n.isscalar(a))

[False False False]
[ True  True  True]
False


In [70]:
#10
a = n.random.randint(0, 15,5)
b = n.random.randint(0, 15,5)
print("Greater Than:")
print(a>b)
print("Less Than:")
print(a<b)
print("Less Than or Equal to:")
print(a<=b)

Greater Than:
[ True False  True  True  True]
Less Than:
[False  True False False False]
Less Than or Equal to:
[False  True False False False]


In [79]:
#11 incomplete
a = n.array([10, 10.0001])
b = n.array([10, 10.00000000001])
print("Equal to:")n.array([10, 10.0001])
print(a==b)
n.isclose(a,b)


Equal to:
[ True False]


array([ True,  True])

In [92]:
#12
a= [1, 7, 13, 105]
a = n.array(a)
print('{} bytes'.format(a.size*a.itemsize))


16 bytes


In [46]:
#13
n.zeros(10)
n.ones(10)
n.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [48]:
#14
n.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [49]:
#15
n.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [25]:
#16
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#17
n.random.rand(1)

array([0.73813072])

In [30]:
#18
n.random.randn(15)

array([-1.30111884, -0.58498933,  1.22329833,  1.12078305, -0.9754812 ,
        0.05270163,  0.55422376, -0.72553878,  2.10183012,  0.79909935,
        0.08514731,  1.71816736,  1.75765127,  2.16991522, -1.60218682])

In [45]:
#19
v = n.arange(15,56)
v[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [69]:
#20
v = n.arange(0,12).reshape(3,4)
for i in n.nditer(v):
    print(i, end=" ")   

0 1 2 3 4 5 6 7 8 9 10 11 

In [44]:
#21
v= n.linspace(5,50,10)
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [53]:
#22
b = n.arange(0,21)
b[9:15] = b[9:15]*-1
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14,  15,  16,  17,  18,  19,  20])

In [91]:
#23
a = n.random.randint(0,10, 5)
a

array([0, 7, 3, 2, 8])

In [112]:
#24
arr = n.random.randint(0, 10, 5)
arr_2 = n.random.randint(0,10, 5)
arr*arr_2

array([ 4, 54,  3,  0,  6])

In [73]:
#25
arr = n.arange(10,22).reshape(3,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [121]:
#26
arr= n.arange(10,56).reshape(2, 23)
rows,columns= arr.shape



(2, 23)

In [78]:
#27
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
#28
a = n.zeros((10, 10))
for i in range(10):
    a[i, 0] = 1
    a[i, 9] = 1
a[0] = 1
a[9] = 1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [87]:
#29
a = n.zeros((5,5))
num = 0
for i in range(5):
    num = num+1
    a[i, i] = num
a

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [113]:
#30
a = n.ones((4,4))
for i in range(4):
    a[i, i] = 0
    if i>=2:
        a[i,i-2] = 0   
    else:
        a[i,i+2] = 0 
a

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [115]:
#31
a = n.random.randint(0, 10,27).reshape(3,3,3)
a

array([[[1, 1, 7],
        [9, 9, 3],
        [0, 5, 1]],

       [[4, 6, 8],
        [9, 4, 0],
        [0, 0, 8]],

       [[8, 5, 5],
        [6, 9, 7],
        [1, 9, 6]]])

In [123]:
#32
a = n.random.randint(0,10,25).reshape(5,5)
print(a.sum(axis= 0))
print(a.sum(axis=1))
print(a.sum())

[20 23 31  8 25]
[23 22 15 22 25]
107


In [132]:
#33
a = n.random.randint(1, 10, 3)
b = n.random.randint(1, 10, 3)
c = [a,b]
total = 1
for i in c:
    for num in i:
        total *= num
print(a,b)
print(total)
a.prod()

[5 7 1] [2 7 9]
4410


35

In [16]:
#34
a = n.random.randint(0,15, (5,5))
print(a)
print("\n")
b = n.random.randint(0,15, 5)
print(b)
print("\n")
a += b
print("New Matrix:")
print(a)

[[13  0 13 11 14]
 [ 5 10 14  4  7]
 [13  6  9  7  5]
 [11  2 14  7  2]
 [ 1 10  9 12  7]]


[ 9 10  8  9  6]


New Matrix:
[[22 10 21 20 20]
 [14 20 22 13 13]
 [22 16 17 16 11]
 [20 12 22 16  8]
 [10 20 17 21 13]]


In [106]:
#36
a = n.arange(2,10)
b = n.arange(12,20)
n.savez_compressed("AYO",x=a, b=b)
with n.load("AYO.npz") as Data:
    x1 = Data["x"]
    x2 = Data["b"]
print(x1)
x2

[2 3 4 5 6 7 8 9]


array([12, 13, 14, 15, 16, 17, 18, 19])

In [109]:
#37
a = n.arange(2,10)
n.savetxt("Ayo.txt",a)
n.loadtxt("Ayo.txt")

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [111]:
#38
a = n.arange(2,10)
n.byte(a)

array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [114]:
#39
a = [1,2,3,4,5,6,7,8,9,10]
b = n.array(a)
c = list(b)
n.allclose(a,c)

True

In [122]:
#40
type(b)

numpy.ndarray

In [136]:
#41
a = n.random.randint(0,5,16).reshape(4,4)
b = a.copy()
print(a)
num = 0
for i in range(4):
    for j in range(4):
        if b[i,j] == 0:
            b[i,j+1] = 
        num += a[i,j]
num

[[0 2 3 0]
 [1 2 4 2]
 [4 4 2 4]
 [1 1 0 2]]


ValueError: cannot convert float NaN to integer

In [29]:
#48
a = n.random.randn(40).reshape(8,5)
a

array([[-1.06742727,  0.45141417, -2.30270902,  0.60432859, -1.20019878],
       [-0.09956563,  0.30015642,  1.0601522 ,  1.02992714,  0.16887276],
       [ 0.85636644, -0.8532558 ,  0.89180244, -0.88091506, -0.5709967 ],
       [-0.62590911, -1.47983353, -0.3237723 , -0.50746911, -0.62275749],
       [-2.5060797 , -2.15035559,  0.94401679, -0.55647255,  0.37831621],
       [-0.32813493,  0.8020947 , -0.12845969,  0.81042078, -0.43526915],
       [ 0.52637337, -0.11904312, -0.22937027,  1.50655379, -0.48370051],
       [ 0.46579173,  0.2843133 ,  0.03409427,  0.94621277,  1.24695397]])

In [70]:
a = n.random.rand(5)
print(a, end="\n" )
print(n.random.choice(25, (2,1)))
a

[0.18094585 0.10291993 0.22289214 0.21049066 0.93420784]
[[17]
 [ 0]]


array([0.18094585, 0.10291993, 0.22289214, 0.21049066, 0.93420784])

In [83]:
#50
a = n.random.randint(0,56,(4,4))
print(a)
b = a.copy()
b[0] = a[-1]
b[-1] = a[0]
b

[[29 49  6 21]
 [47 53 52 18]
 [20 55 15  4]
 [31 18 21 28]]


array([[31, 18, 21, 28],
       [47, 53, 52, 18],
       [20, 55, 15,  4],
       [29, 49,  6, 21]])

In [98]:
#51
a = n.arange(1,31).reshape(5,6)
a.fill(0)
a

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [113]:
#52
a = n.random.randint(1,31, 30).reshape(5,6)
print(a, end="\n")
#sorting by columns
print('Sorted by columns')
a.sort(axis=0)
print(a)
#sorting by rows
print('Sorted by rows')
a.sort(axis=1)
print(a)


[[ 1  4 10 16 24 20]
 [16 17 21  7 15 17]
 [14 19 11 28 26 14]
 [22 17  5 12 14 27]
 [12 28 29  2 26  2]]
Sorted by columns
[[ 1  4  5  2 14  2]
 [12 17 10  7 15 14]
 [14 17 11 12 24 17]
 [16 19 21 16 26 20]
 [22 28 29 28 26 27]]
Sorted by rows
[[ 1  2  2  4  5 14]
 [ 7 10 12 14 15 17]
 [11 12 14 17 17 24]
 [16 16 19 20 21 26]
 [22 26 27 28 28 29]]


In [130]:
#53
sn = 7
a = n.arange(15)
a[a!=sn]

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14])

In [136]:
#54
sn = 7
rn = 6
a = n.arange(15)
b = []
for i in a:
    if i > sn:
        i = rn
        b.append(i)
    else:
        i = rn
        b.append(i)
n.array(b)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [135]:
#also 54
rn = 6
a = n.arange(15)
a[:] = rn
a

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [141]:
#56
a = n.arange(60).reshape(3,5,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [148]:
#57
a = n.arange(16).reshape(4,4)
print(a)
b = a.copy()
b[:,0] = a[:,-1]
b[:,-1] = a[:,0]
b[:,1] = a[:,2]
b[:,2] = a[:,1]
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [161]:
#58
a = n.arange(16).reshape(4,4)
a.transpose((1, 0))

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [165]:
#59
ar = n.arange(1,7)
arr_2 = n.arange(7,13)
if len(ar) == len(arr_2):
    print(ar*arr_2)

[ 7 16 27 40 55 72]
